export const INIT_GAME_SETTINGS = 'INIT_GAME_SETTINGS';
export const SAVE_GAME_SETTINGS = 'SAVE_GAME_SETTINGS';
export const INIT_USER_SETTINGS = 'INIT_USER_SETTINGS';
export const SAVE_USER_SETTINGS = 'SAVE_USER_SETTINGS';

export const NEW_GAME = 'NEW_GAME';
export const NEXT_TURN = 'NEXT_TURN';
export const CHOOSE_ANSWER = 'CHOOSE_ANSWER';

export const SET_SESSION = 'SET_SESSION';
export const SET_CONNECTION = 'SET_CONNECTION';
export const SET_REQUEST_COUNT = 'SET_REQUEST_COUNT';